### ISSUE TITLE
Stage raw sequencing reads on usegalaxy

### ISSUE THREAD

**Issue by rvosa** [naturalis/mtdna-reference-database#3]
- P1_S7 https://www.dropbox.com/s/0g6q0s79ec09nz2/P1_S7_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/4h1f5uah9icc7wy/P1_S7_L001_R2_001.fastq.gz?dl=0
- P2_S8 https://www.dropbox.com/s/g88ob7aa7ux1rxq/P2_S8_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/nnho4vbqqq0w2fz/P2_S8_L001_R2_001.fastq.gz?dl=0
- P3_S9 GOAT
- P5_S6 https://www.dropbox.com/s/07ge3r1gycjmk1k/P5_S6_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/tu4zlpstf4w43p9/P5_S6_L001_R2_001.fastq.gz?dl=0
- P195_S1 https://www.dropbox.com/s/0xlagobo8w4q7z0/P195_S1_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/rtb4thbj9z7pvuv/P195_S1_L001_R2_001.fastq.gz?dl=0
- P700_S2 https://www.dropbox.com/s/g0sg60nxxr4oee9/P700_S2_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/gxt37icnv59o3me/P700_S2_L001_R2_001.fastq.gz?dl=0
- P786_S5 https://www.dropbox.com/s/fo8k0di1i6a3fdg/P786_S5_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/jjt2sc96z0l7v4p/P786_S5_L001_R2_001.fastq.gz?dl=0
- P78404_S3 https://www.dropbox.com/s/241o2o90cbzu3nr/P78404_S3_L001_R1_001.fastq.gz?dl=0,
https://www.dropbox.com/s/o8ab0u6cokufaw9/P78404_S3_L001_R2_001.fastq.gz?dl=0
- P78406_S4 https://www.dropbox.com/s/02un1gdjja9qpra/P78406_S4_L001_R1_001.fastq.gz?dl=0, https://www.dropbox.com/s/urbxshs2ilidcvj/P78406_S4_L001_R2_001.fastq.gz?dl=0

**Comment by rvosa** [comment]
This is paired-end FASTQ data with raw sequencing reads. For each sample there are two files (fw/rev). These need to be groomed in galaxy and then mapped against the FASTA reference.

**Comment by HaoqingDu** [comment]
Uploaded all raw sequences onto Galaxy. Will check with Rutger on Wednesday's meeting.
