### ISSUE TITLE
Stage reference genome on usegalaxy

### ISSUE THREAD

**Issue by rvosa** [naturalis/mtdna-reference-database#4]
https://www.dropbox.com/s/2wmul5uysv4r4tm/ARS-UCD1.2_Btau5.0.1Y.MT.fa.gz?dl=0

**Comment by rvosa** [comment]
This is the same reference genome as used by 1000 bulls project, but then only mtDNA. In FASTA format. Used for mapping the raw reads against.

**Comment by HaoqingDu** [comment]
Uploaded the reference onto Galaxy. will check with Rutger on Wednesday.
