### ISSUE TITLE
Cleanup background panel table

### ISSUE THREAD

**Issue by rvosa** [naturalis/mtdna-reference-database#6]
This table is a rough aggregation of metadata about samples from the 1000 bull project: https://www.dropbox.com/s/9urr0yes6x1www4/breeds-filtered.txt?dl=0

Clean up this table so that:
- breed name is always in the same column
- there are always 3 samples per breed
- there is a column with at least country (in France region?) of origin

The sample names in the first column correspond with the samples in the SNPs file from #5, which we want to filter to keep the samples we want.

**Comment by HaoqingDu** [comment]
See the tsv file **Breed_Coutry_Region** in the doc folder
