### ISSUE TITLE
Share galaxy history with Rutger

### ISSUE THREAD

**Issue by rvosa** [naturalis/mtdna-reference-database#7]
<img width="372" alt="Screenshot 2023-05-04 at 20 08 52" src="https://user-images.githubusercontent.com/106490/236291574-2d44796b-6245-423a-ac1e-42a9a75c7b68.png">

Share with user rutgeraldo@gmail.com

**Comment by HaoqingDu** [comment]
Have already shared with rutgeraldo@gmail.com
